### ISSUE TITLE
[ BUILD APP ACTION ] Manque une étape

### ISSUE THREAD

**Issue by JeromeMSD** [tom-rh/4A_ILC_PROJET_CI_CD#2]
Dans https://github.com/tom-rh/4A_ILC_PROJET_CI_CD/blob/main/.github/workflows/build_application.yml
Il vous manque une étape pour que cette action soit pertinente. 

```yaml
      # Install Flask
      - name: Install flask
        run: pip install flask
```

Ici vous ne testez que le fait que `flask` puisse s'installer dans le runner GitHub. Pour tester la syntaxe du code, il vous faut une étape supplémentaire qui exécute le fichier `api.py` **sans** lancer le serveur, comme nous l'avions fait dans le TD3 et le TD4 dont la correction est sur le dépôt module_ci-cd : 

```python
if __name__ == '__main__':
	if len(sys.argv) > 1:
		if sys.argv[1] == "check_syntax":
			print("Build [ OK ]")
			exit(0)
		else:
			print("Passed argument not supported ! Supported argument : check_syntax")
			exit(1)
	app.run(debug=True)
```

Ainsi vous auriez pu ainsi tester la syntax de votre fichier `api.py` en ajoutant l'étape suivante dans votre Github Action : 

```yaml
jobs:
    ...
    steps:
    ...
    - name: [ API ] Check syntax 
      run: |
        python api.py check_syntax
```
